// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXVBNvQy8rTqbj4amapemE8PweBqIggIE',
    appId: '1:733575404883:web:def1839de0c8e15d6255a6',
    messagingSenderId: '733575404883',
    projectId: 'list-database-deed7',
    authDomain: 'list-database-deed7.firebaseapp.com',
    storageBucket: 'list-database-deed7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHll4h7wZvnm274oHlk2yxtuAp3jq5-N4',
    appId: '1:733575404883:android:5356e9a448410ab46255a6',
    messagingSenderId: '733575404883',
    projectId: 'list-database-deed7',
    storageBucket: 'list-database-deed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQLVCCE8KVA3TNz9Sslfzzs5fFO4brsng',
    appId: '1:733575404883:ios:ff9b5c6bb3d53f996255a6',
    messagingSenderId: '733575404883',
    projectId: 'list-database-deed7',
    storageBucket: 'list-database-deed7.appspot.com',
    iosBundleId: 'com.example.listDatabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQLVCCE8KVA3TNz9Sslfzzs5fFO4brsng',
    appId: '1:733575404883:ios:8e9de1264b225cc76255a6',
    messagingSenderId: '733575404883',
    projectId: 'list-database-deed7',
    storageBucket: 'list-database-deed7.appspot.com',
    iosBundleId: 'com.example.listDatabase.RunnerTests',
  );
}
